### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by otavionestares** [Ziggeo/ZiggeoRubySdk#5]
Hello!

I'm trying to make the recorder responsive but without sucess... 
Here's my code: 

`<ziggeorecorder
     ziggeo-responsive=1
     ziggeo-width=573
     ziggeo-height=433          
     ziggeo-timelimit=600
     ziggeo-theme="elevate"
     ziggeo-primaryrecord=true
     ziggeo-input_bind='video_detail[video_path]'
     ziggeo-perms="allowupload"></ziggeorecorder>`

On you documentation you instruct to use only "Ziggeo", but with this option I can't choose a theme and even configuration like "timelimit" doesn't works... 

Best

**Comment by Bane-D** [comment]
Hi,

In regards to the responsive. Can you please try it out without setting the width and height?

That should make it just adjust to the other elements on the page.

I believe that this will solve it however please do let us know how that goes and we can work through the rest as well :)

Cheers,
Bane

**Comment by ntshcalleia** [comment]
Responsive was removed on v2 and replaced by stretch parameters.
